#!/usr/bin/env bash

###################################################
### helper functions                            ###
###################################################

usage () {
  cat <<EOF
linux-restore [-m <machine-name>] [-b] [-y]

   -m <machine-name> machine config to use. (default* | labcg | SeARCH | raspbian)
   -s <shell-name> shell to use (zsh* | bash)
   -y skip confirmations
   -b backup every replaced file
   -h show this
EOF

}

die () {
    echo >&2 "$@"
    exit 1
}

# currently just an alias to `echo`
log () {
  echo "$@"
}

# creates a symlink backing up original dest file if it exists
make_ln () {
  src=$1
  dst=$2
  # backup current file if exists
  if [ -e $dst ] || [ -L $dst ]; then
    rm -rf $dst.bak
    if ! $clean; then
      mv $dst $dst.bak
    else
      rm -rf $dst
    fi
  fi

  # create link
  ln -s $src $dst
}

# asks for confirmation on a task. executes function if positive
op_ask () {
  prompt=$1
  function=$2

  yes=false

  if ! $force_yes; then
    # read arg
    op="dummy"
    until [[ $op =~ ^[yYnN]$ ]]; do
      read -p "$1 [y/n] " op
    done

    # check confirmation and exec function
    if [[ $op =~ ^[yY]$ ]]; then
      $function
    fi
  else
    yes=true
  fi

  if $yes; then
    $function
  fi
}

###################################################
### Parse Args                                  ###
###################################################

# argument string for getopts
opts="hm:s:by"

machine_name="default"
shell_name="zsh"
force_yes=false
clean=true

while getopts $opts option; do
  case $option in
    m)
      machine_name=$OPTARG
      ;;
    s)
      shell_name=$OPTARG
      ;;
    b)
      clean=false
     ;;
    y)
      clean=false
      force_yes=true
      ;;
    h)
      usage
      exit
      ;;
    ?)
      usage
      die "error: invalid argument $OPTARG"
      ;;
  esac
done


###################################################
### Initial Setup                               ###
###################################################

# path for the global symlink that will be created
config="$HOME/.config"
mkdir -p $config
myunix="$config/my-unix"
machine="$myunix/machines/$machine_name"

# absolute path to this script
abspath="$(cd "${0%/*}" 2>/dev/null; echo "$PWD")"

make_ln $abspath $myunix

echo "installing..."

###################################################
### zsh / oh-my-zshx                            ###
###################################################
if [ "$shell_name" == "zsh" ]; then
  url="https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh"
  file=oh-my-zsh.install.sh
  wget –no-check-certificate $url -o /dev/null -O $file
  chmod +x $file
  ./$file
  rm $file
fi

###################################################
### home sym links                              ###
###################################################

for file in $(ls $myunix/home); do
  echo "   ${file}"
  make_ln $myunix/home/$file $HOME/.$file
done

# fix ssh dir permissions
chmod 700 $HOME/.ssh
chmod 644 $HOME/.ssh/id_rsa.pub

###################################################
### machine custom script                       ###
###################################################

apt_purge () {
  echo "   purging unused packages"
  cat $machine/apt_purge | xargs sudo apt-get --yes purge
  sudo apt-get --yes autoremove
  sudo apt-get --yes autoclean
  sudo apt-get --yes clean
}

apt_update () {
  echo "   apt update"
  sudo apt-get update
  echo "   apt upgrade"
  sudo apt-get upgrade
  echo "   apt dist-upgrade"
  sudo apt-get dist-upgrade
}

apt_install () {
  echo "   apt package install"
  cat $machine/apt_install | xargs sudo apt-get --yes install
}

rvm () {
  log "   rvm"
  curl -L https://get.rvm.io | bash -s stable --ruby
}

spf13vim () {
  log "   spf13-vim"
  path=$PWD
  cd ~
  curl http://j.mp/spf13-vim3 -L -o - | sh
  cd $path
}

echo -e "\nSetting up machine-specifics using $machine"
source $machine/install.sh

###################################################
### finalize                                    ###
###################################################
log "all done! restart your terminal to see the changes"
