#!/bin/bash

###################################################
### helper functions                            ###
###################################################

function die {
    echo >&2 "$@"
    exit 1
}

# currently just an alias to `echo`
function log {
	echo $@
}

# creates a symlink backing up original dest file if it exists
function ln_bak {
	ln_source=$1
	ln_dest=$2
	# backup current file if exists
	if [ -e $ln_dest ]
		mv $ln_dest $ln_dest.ln_bak
	fi

	# create link
	ln -s $ln_src $ln_dst
}

# asks for confirmation on a task. executes function if positive
function op_ask {
	prompt=$1
	function=$2

	# read arg
	op="dummy"
	until [[ $op =~ ^[yYnN]$ ]]; do
		read -p "$1 [y/n] " op
	done

	# check confirmation and exec function
	if [[ $op =~ ^[yY]$ ]]; then
		$function
	fi
}

###################################################
### Initial Setup                               ###
###################################################

# $1 should be machine_name, otherwise "default" is used
machine_name="default"
if [ "$#" -eq 1 ]; then
	machine_name=$1
fi

# by default, installs for current user
user=`whoami`

# path to home dir of user
home="/home/$user"

# path for the global symlink that will be created
config="$home/.config"
myconfig="$config/linux-restore"
machine="$myconfig/machines/$machine_name"

# absolute path to this script
abspath="$(cd "${0%/*}" 2>/dev/null; echo "$PWD")"


log "installing for $user"

#
# create global symlink
#
if [ ! -d $config ]; then
	log "$config dir does not yet exist. creating"
fi

log "global symlink will be on $myconfig"
ln_bak $abspath $myconfig

log "installing..."

###################################################
### rc installation                             ###
###################################################

log "   bashrc"
ln_bak $myconfig/rc/bashrc $home/.bashrc

log "   vimrc"
ĺn_bak $myconfig/rc/vimrc $home/.vimrc

###################################################
### sym links                                   ###
###################################################

log "  .vim dir"
ln_bak $myconfig/misc/vim $home/.vim

log "   .bin dir"
ln_bak $machine/bin $home/.bin

log "   .ssh dir"
ln_bak $myconfig/ssh $home/.ssh

# fix ssh dir permissions
chmod 700 $home/.ssh
chmod 644 $home/.ssh/id_rsa.pub

###################################################
### machine custom script                       ###
###################################################

$machine/install.sh