#!/bin/bash

###################################################
### helper functions                            ###
###################################################

function die {
    echo >&2 "$@"
    exit 1
}

# currently just an alias to `echo`
function log {
	echo $@
}

# creates a symlink backing up original dest file if it exists
function ln_bak {
	src=$1
	dst=$2
	# backup current file if exists
	if [ -e $dst ]; then
		mv $dst $dst.bak
	fi

	# create link
	ln -s $src $dst
}

# asks for confirmation on a task. executes function if positive
function op_ask {
	prompt=$1
	function=$2

	# read arg
	op="dummy"
	until [[ $op =~ ^[yYnN]$ ]]; do
		read -p "$1 [y/n] " op
	done

	# check confirmation and exec function
	if [[ $op =~ ^[yY]$ ]]; then
		$function
	fi
}


###################################################
### Initial Setup                               ###
###################################################

# $1 should be machine_name, otherwise "default" is used
machine_name="default"
if [ "$#" -eq 1 ]; then
	machine_name=$1
fi

# by default, installs for current user
user=`whoami`

# path to home dir of user
home="/home/$user"

# path for the global symlink that will be created
config="$home/.config"
myconfig="$config/linux-restore"
machine="$myconfig/machines/$machine_name"

# custom rc file
myrc="$home/.naps62rc"

# absolute path to this script
abspath="$(cd "${0%/*}" 2>/dev/null; echo "$PWD")"


log "installing for $user"

#
# create global symlink
#
if [ ! -d $config ]; then
	log "$config dir does not yet exist. creating"
fi

log "global symlink will be on $myconfig"
ln_bak $abspath $myconfig

log "installing..."

###################################################
### rc installation                             ###
###################################################

# creates ~/.naps62rc
# this file is machine dependent and is not intended to be changed
# so there is no problem in generating it instead of hard-creating
log "   creating env file .naps62rc"
ln_bak $myconfig/files/rc/naps62rc.template $myrc
sed -i "s,<configdir>,$myconfig,"     $myrc
sed -i "s,<rcdir>,$myconfig/files/rc" $myrc
sed -i "s,<machine>,$machine_name,"   $myrc
sed -i "s,<machinedir>,$machine,"     $myrc

log "   bashrc"
ln_bak $myconfig/files/rc/bashrc $home/.bashrc


###################################################
### sym links                                   ###
###################################################

log "   vimrc"
ĺn_bak $myconfig/files/rc/vimrc $home/.vimrc

log "  .vim dir"
ln_bak $myconfig/files/vim $home/.vim

log "   .bin dir"
ln_bak $myconfig/files/bin $home/.bin

log "   .ssh dir"
ln_bak $myconfig/files/ssh $home/.ssh

# fix ssh dir permissions
chmod 700 $home/.ssh
chmod 644 $home/.ssh/id_rsa.pub

###################################################
### machine custom script                       ###
###################################################

. $machine/install.sh