#!/usr/bin/env bash

export NAPS62_CONFDIR=$HOME/.config/my-unix
export NAPS62_SHELL=bash

function bash_reload {
  source ${NAPS62_CONFDIR}/files/shell/env
  source ${NAPS62_CONFDIR}/files/shell/cmds
  source ${NAPS62_CONFDIR}/files/shell/bash/aliases
  source ${NAPS62_CONFDIR}/files/shell/bash/defaults
  source ${NAPS62_CONFDIR}/files/shell/bash/history

  # interactive-only stuff
  [[ $- == *i* ]] || return
  source ${NAPS62_CONFDIR}/files/shell/bash/colors
  source ${NAPS62_CONFDIR}/files/shell/bash/ps1
}

export UPLAY_DEV_MAIL_USERNAME='uplay.dev@gmail.com'
export UPLAY_DEV_MAIL_PASSWORD='baterpunho'
#bash_reload
