#!/usr/bin/env zsh

export NAPS62_CONFDIR=$HOME/.config/my-unix
export NAPS62_SHELL=zsh

function zsh_reload {
  source ${NAPS62_CONFDIR}/files/shell/zsh/defaults
  source ${NAPS62_CONFDIR}/files/shell/env
  source ${NAPS62_CONFDIR}/files/shell/cmds
  source ${NAPS62_CONFDIR}/files/shell/zsh/aliases

  source ${NAPS62_CONFDIR}/files/shell/zsh/history

  # interactive-only stuff
  [[ $- == *i* ]] || return
  source ${NAPS62_CONFDIR}/files/shell/zsh/prompt
}

export COINBASE_API_KEY=c6b434d42c4be78dc0badb9e5a2faf0a1373abf318f1381d6382741a01f3c98d

zsh_reload
