#!/bin/bash

alias reboot='sudo reboot'
alias halt='sudo poweroff'

alias apt='sudo aptitude'
alias open='xdg-open'

# one-char aliases
alias g='git'
alias r='rails'
alias o='open'

# git
alias gst='git status'
alias gpl='git pull'
alias gps='git push'
alias gcm='git commit'

# cd
alias cd='cdls'
alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'

# auto colors
alias ls='ls --color=always'
alias dir='dir --color=always'
alias vdir='vdir --color=always'
alias grep='grep --color=always'
alias fgrep='fgrep --color=always'
alias egrep='egrep --color=always'

# ls
alias ll='ls -alF'
alias la='ls -A'
alias lla='la -AlF'


# alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# proxy
alias proxy='source ${NAPS62_CONFDIR}/home/bin/proxy'
