$pdf_mode        = 1;
$postscript_mode = 0;
$dvi_mode        = 0;
@default_files   = ('main.tex');
$pdflatex        = 'rubber -c "setlist arguments --shell-escape" --force --pdf %S';
$pdf_previewer   = 'open %S 2> /dev/null';
$max_repeat=2;

# without rubber
#$aux_dir         = 'output';
#$out_dir         = 'output';
#$pdflatex        = 'mkdir -p output; pdflatex -shell-escape %O %S';
