#!/usr/bin/env sh

alias reboot='sudo reboot'
alias halt='sudo poweroff'

alias apt='sudo aptitude'
alias open='xdg-open'

# one-char aliases
alias g='git'
alias o='open'
alias v='vim'
alias m='make'
alias r='rails'
alias rk='rake'

# cd
alias cd='cdls'
alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'

# ls
alias ll='ls -alF'
alias la='ls -A'
alias lla='la -AlF'


# alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# proxy
alias proxy='source ${NAPS62_CONFDIR}/home/bin/proxy'

# git
# alias git=hub

# vim
# proxy to enable usage of Ctrl-S shortcut
alias vim="stty stop '' -ixoff ; vim"
