#!/usr/bin/env zsh

# zsh-git-prompt, by olivierverdier @ github
source $NAPS62_CONFDIR/files/shell/zsh/git_prompt/zsh-git-prompt.sh

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}("
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$fg_bold[blue]%})"
ZSH_THEME_GIT_PROMPT_SEPARATOR="%{$fg_bold[blue]%}|"
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_bold[red]%}"
ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[red]%}•"
ZSH_THEME_GIT_PROMPT_CONFLICTS="%{$fg[red]%}✕"
ZSH_THEME_GIT_PROMPT_CHANGED="%{$fg[blue]%}+"
ZSH_THEME_GIT_PROMPT_REMOTE=""
ZSH_THEME_GIT_PROMPT_UNTRACKED="…"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[green]%}✔"

repo_name () {
  basename $(git remote show -n origin 2>/dev/null | grep Push | cut -d: -f2-) 2>/dev/null
}

prompt_char () {
  git branch >/dev/null 2>/dev/null && echo '±' && return
}

case ${SOLARIZED_THEME:-dark} in
    light) bkg=white;;
    *)     bkg=black;;
esac


export ZSH_THEME_GIT_PROMPT_NOCACHE=1
#PROMPT='%{$fg_bold[cyan]%}%c%{$fg_bold[blue]%} %{$fg_bold[blue]%}%# %{$reset_color%}'
#RPROMPT='%{$fg_bold[blue]%}$(repo_name)%{$reset_color%}$(git_super_status)%{$reset_color%}'

PROMPT='
%{%B%F{green}%}%n %{%B%F{green}%}%{%B%F{blue}%}%~%{%B%F{green}%}%E%{%f%k%b%}
%{%B%F{blue}%} %#%{%f%k%b%} '
RPROMPT='%{$fg_bold[blue]%}$(repo_name)%{$reset_color%}$(git_super_status)%{$reset_color%}'
